// flow-typed signature: 10b496e16b08e61048824bdb1fca5bcf
// flow-typed version: <<STUB>>/@playlyfe/gql_v^2.6.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@playlyfe/gql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@playlyfe/gql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@playlyfe/gql/lib/cli/cli' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/cli/gql-client' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/cli/gql-server' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/cli/rpc/Client' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/cli/rpc/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/cli/rpc/Server' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/config/GQLConfig' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/GQLService' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/_shared/createRelaySchema' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/_shared/getTokenAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/_shared/getTypeInfo' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/_shared/parseQuery' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/_shared/Parsers/EmbeddedQueryParser' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/_shared/Parsers/newParser' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/_shared/Parsers/QueryParser' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/_shared/types' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/commands/getDefinitionAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/commands/getHintsAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/commands/getInfoOfTokenAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/commands/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/QueryManager' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/validation/rules/_shared/replaceRules' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query-relay/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query-relay/ProvidedNonNullArguments' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query-relay/ScalarLeafs' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query/ArgumentsOfCorrectType' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/query/validation/validate' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/_shared/getTokenAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/_shared/SchemaParser' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/commands/findRefsOfTokenAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/commands/getDefinitionAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/commands/getHintsAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/commands/getInfoOfTokenAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/commands/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/SchemaBuilder/buildASTSchema' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/SchemaBuilder/getNamedTypeNode' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/SchemaBuilder/GQLSchema' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/SchemaBuilder/GQLSchemaBuilder' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/SchemaBuilder/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/SchemaBuilder/PlaceholderTypes' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/validation/rules/gql-rules-schema/index' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/validation/rules/gql-rules-schema/NoUnusedTypeDefinition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/schema/validation/validate' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/createValidate' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/debug' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/EmbeddedLanguageParser' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/getDefLocationForNode' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/getTokenAtPosition' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/GQLError' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/GQLTypes' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/MultilineCharacterStream' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/printTokenState' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/splitLines' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/toOffset' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/types' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/typeToName' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/watch' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/shared/whileSafe' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/tools/generate/generateFlowTypes' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/tools/generate/generateSchemaGQL' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/tools/generate/generateSchemaJSON' {
  declare module.exports: any;
}

declare module '@playlyfe/gql/lib/tools/generate/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@playlyfe/gql/lib/cli/cli.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/cli/cli'>;
}
declare module '@playlyfe/gql/lib/cli/gql-client.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/cli/gql-client'>;
}
declare module '@playlyfe/gql/lib/cli/gql-server.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/cli/gql-server'>;
}
declare module '@playlyfe/gql/lib/cli/rpc/Client.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/cli/rpc/Client'>;
}
declare module '@playlyfe/gql/lib/cli/rpc/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/cli/rpc/index'>;
}
declare module '@playlyfe/gql/lib/cli/rpc/Server.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/cli/rpc/Server'>;
}
declare module '@playlyfe/gql/lib/config/GQLConfig.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/config/GQLConfig'>;
}
declare module '@playlyfe/gql/lib/GQLService.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/GQLService'>;
}
declare module '@playlyfe/gql/lib/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/index'>;
}
declare module '@playlyfe/gql/lib/query/_shared/createRelaySchema.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/_shared/createRelaySchema'>;
}
declare module '@playlyfe/gql/lib/query/_shared/getTokenAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/_shared/getTokenAtPosition'>;
}
declare module '@playlyfe/gql/lib/query/_shared/getTypeInfo.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/_shared/getTypeInfo'>;
}
declare module '@playlyfe/gql/lib/query/_shared/parseQuery.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/_shared/parseQuery'>;
}
declare module '@playlyfe/gql/lib/query/_shared/Parsers/EmbeddedQueryParser.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/_shared/Parsers/EmbeddedQueryParser'>;
}
declare module '@playlyfe/gql/lib/query/_shared/Parsers/newParser.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/_shared/Parsers/newParser'>;
}
declare module '@playlyfe/gql/lib/query/_shared/Parsers/QueryParser.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/_shared/Parsers/QueryParser'>;
}
declare module '@playlyfe/gql/lib/query/_shared/types.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/_shared/types'>;
}
declare module '@playlyfe/gql/lib/query/commands/getDefinitionAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/commands/getDefinitionAtPosition'>;
}
declare module '@playlyfe/gql/lib/query/commands/getHintsAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/commands/getHintsAtPosition'>;
}
declare module '@playlyfe/gql/lib/query/commands/getInfoOfTokenAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/commands/getInfoOfTokenAtPosition'>;
}
declare module '@playlyfe/gql/lib/query/commands/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/commands/index'>;
}
declare module '@playlyfe/gql/lib/query/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/index'>;
}
declare module '@playlyfe/gql/lib/query/QueryManager.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/QueryManager'>;
}
declare module '@playlyfe/gql/lib/query/validation/rules/_shared/replaceRules.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/validation/rules/_shared/replaceRules'>;
}
declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query-relay/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/validation/rules/gql-rules-query-relay/index'>;
}
declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query-relay/ProvidedNonNullArguments.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/validation/rules/gql-rules-query-relay/ProvidedNonNullArguments'>;
}
declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query-relay/ScalarLeafs.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/validation/rules/gql-rules-query-relay/ScalarLeafs'>;
}
declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query/ArgumentsOfCorrectType.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/validation/rules/gql-rules-query/ArgumentsOfCorrectType'>;
}
declare module '@playlyfe/gql/lib/query/validation/rules/gql-rules-query/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/validation/rules/gql-rules-query/index'>;
}
declare module '@playlyfe/gql/lib/query/validation/validate.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/query/validation/validate'>;
}
declare module '@playlyfe/gql/lib/schema/_shared/getTokenAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/_shared/getTokenAtPosition'>;
}
declare module '@playlyfe/gql/lib/schema/_shared/SchemaParser.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/_shared/SchemaParser'>;
}
declare module '@playlyfe/gql/lib/schema/commands/findRefsOfTokenAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/commands/findRefsOfTokenAtPosition'>;
}
declare module '@playlyfe/gql/lib/schema/commands/getDefinitionAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/commands/getDefinitionAtPosition'>;
}
declare module '@playlyfe/gql/lib/schema/commands/getHintsAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/commands/getHintsAtPosition'>;
}
declare module '@playlyfe/gql/lib/schema/commands/getInfoOfTokenAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/commands/getInfoOfTokenAtPosition'>;
}
declare module '@playlyfe/gql/lib/schema/commands/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/commands/index'>;
}
declare module '@playlyfe/gql/lib/schema/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/index'>;
}
declare module '@playlyfe/gql/lib/schema/SchemaBuilder/buildASTSchema.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/SchemaBuilder/buildASTSchema'>;
}
declare module '@playlyfe/gql/lib/schema/SchemaBuilder/getNamedTypeNode.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/SchemaBuilder/getNamedTypeNode'>;
}
declare module '@playlyfe/gql/lib/schema/SchemaBuilder/GQLSchema.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/SchemaBuilder/GQLSchema'>;
}
declare module '@playlyfe/gql/lib/schema/SchemaBuilder/GQLSchemaBuilder.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/SchemaBuilder/GQLSchemaBuilder'>;
}
declare module '@playlyfe/gql/lib/schema/SchemaBuilder/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/SchemaBuilder/index'>;
}
declare module '@playlyfe/gql/lib/schema/SchemaBuilder/PlaceholderTypes.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/SchemaBuilder/PlaceholderTypes'>;
}
declare module '@playlyfe/gql/lib/schema/validation/rules/gql-rules-schema/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/validation/rules/gql-rules-schema/index'>;
}
declare module '@playlyfe/gql/lib/schema/validation/rules/gql-rules-schema/NoUnusedTypeDefinition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/validation/rules/gql-rules-schema/NoUnusedTypeDefinition'>;
}
declare module '@playlyfe/gql/lib/schema/validation/validate.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/schema/validation/validate'>;
}
declare module '@playlyfe/gql/lib/shared/createValidate.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/createValidate'>;
}
declare module '@playlyfe/gql/lib/shared/debug.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/debug'>;
}
declare module '@playlyfe/gql/lib/shared/EmbeddedLanguageParser.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/EmbeddedLanguageParser'>;
}
declare module '@playlyfe/gql/lib/shared/getDefLocationForNode.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/getDefLocationForNode'>;
}
declare module '@playlyfe/gql/lib/shared/getTokenAtPosition.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/getTokenAtPosition'>;
}
declare module '@playlyfe/gql/lib/shared/GQLError.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/GQLError'>;
}
declare module '@playlyfe/gql/lib/shared/GQLTypes.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/GQLTypes'>;
}
declare module '@playlyfe/gql/lib/shared/MultilineCharacterStream.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/MultilineCharacterStream'>;
}
declare module '@playlyfe/gql/lib/shared/printTokenState.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/printTokenState'>;
}
declare module '@playlyfe/gql/lib/shared/splitLines.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/splitLines'>;
}
declare module '@playlyfe/gql/lib/shared/toOffset.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/toOffset'>;
}
declare module '@playlyfe/gql/lib/shared/types.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/types'>;
}
declare module '@playlyfe/gql/lib/shared/typeToName.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/typeToName'>;
}
declare module '@playlyfe/gql/lib/shared/watch.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/watch'>;
}
declare module '@playlyfe/gql/lib/shared/whileSafe.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/shared/whileSafe'>;
}
declare module '@playlyfe/gql/lib/tools/generate/generateFlowTypes.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/tools/generate/generateFlowTypes'>;
}
declare module '@playlyfe/gql/lib/tools/generate/generateSchemaGQL.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/tools/generate/generateSchemaGQL'>;
}
declare module '@playlyfe/gql/lib/tools/generate/generateSchemaJSON.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/tools/generate/generateSchemaJSON'>;
}
declare module '@playlyfe/gql/lib/tools/generate/index.js' {
  declare module.exports: $Exports<'@playlyfe/gql/lib/tools/generate/index'>;
}
