// flow-typed signature: c71ff94c84b667d98804516fa441c32b
// flow-typed version: <<STUB>>/aws-amplify_v^1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-amplify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-amplify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-amplify/dist/aws-amplify' {
  declare module.exports: any;
}

declare module 'aws-amplify/dist/aws-amplify.min' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-amplify/dist/aws-amplify.js' {
  declare module.exports: $Exports<'aws-amplify/dist/aws-amplify'>;
}
declare module 'aws-amplify/dist/aws-amplify.min.js' {
  declare module.exports: $Exports<'aws-amplify/dist/aws-amplify.min'>;
}
declare module 'aws-amplify/lib/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/index'>;
}
