// flow-typed signature: e5644f58791da297d90b6f393de9a96e
// flow-typed version: <<STUB>>/babel-plugin-grommet_v^0.5.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-grommet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-grommet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-grommet/index' {
  declare module.exports: $Exports<'babel-plugin-grommet'>;
}
declare module 'babel-plugin-grommet/index.js' {
  declare module.exports: $Exports<'babel-plugin-grommet'>;
}
