// flow-typed signature: 4586903cc84625ae9aa0fb273d36a8c3
// flow-typed version: <<STUB>>/convert-time_v^0.3.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'convert-time'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'convert-time' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'convert-time/test/convert_time_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'convert-time/index' {
  declare module.exports: $Exports<'convert-time'>;
}
declare module 'convert-time/index.js' {
  declare module.exports: $Exports<'convert-time'>;
}
declare module 'convert-time/test/convert_time_test.js' {
  declare module.exports: $Exports<'convert-time/test/convert_time_test'>;
}
