// flow-typed signature: c27e10f3056690775da4697f02f3de56
// flow-typed version: <<STUB>>/cypress-testing-library_v^2.2.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-testing-library/add-commands' {
  declare module.exports: any;
}

declare module 'cypress-testing-library/dist/add-commands' {
  declare module.exports: any;
}

declare module 'cypress-testing-library/dist/index' {
  declare module.exports: any;
}

declare module 'cypress-testing-library/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-testing-library/add-commands.js' {
  declare module.exports: $Exports<'cypress-testing-library/add-commands'>;
}
declare module 'cypress-testing-library/dist/add-commands.js' {
  declare module.exports: $Exports<'cypress-testing-library/dist/add-commands'>;
}
declare module 'cypress-testing-library/dist/index.js' {
  declare module.exports: $Exports<'cypress-testing-library/dist/index'>;
}
declare module 'cypress-testing-library/dist/utils.js' {
  declare module.exports: $Exports<'cypress-testing-library/dist/utils'>;
}
