// flow-typed signature: af7d1eff3e1f1d9641f9fe5a03d76c87
// flow-typed version: <<STUB>>/jest-each_v^23.4.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-each'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-each' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-each/build/bind' {
  declare module.exports: any;
}

declare module 'jest-each/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-each/build/bind.js' {
  declare module.exports: $Exports<'jest-each/build/bind'>;
}
declare module 'jest-each/build/index.js' {
  declare module.exports: $Exports<'jest-each/build/index'>;
}
