// flow-typed signature: d27c7d7baddef5f21f5eb871ca1b23bd
// flow-typed version: <<STUB>>/makecancelable_v^1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'makecancelable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'makecancelable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'makecancelable/dist/flushPromises' {
  declare module.exports: any;
}

declare module 'makecancelable/dist/makeCancelable' {
  declare module.exports: any;
}

declare module 'makecancelable/dist/makeCancelable.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'makecancelable/dist/flushPromises.js' {
  declare module.exports: $Exports<'makecancelable/dist/flushPromises'>;
}
declare module 'makecancelable/dist/makeCancelable.js' {
  declare module.exports: $Exports<'makecancelable/dist/makeCancelable'>;
}
declare module 'makecancelable/dist/makeCancelable.test.js' {
  declare module.exports: $Exports<'makecancelable/dist/makeCancelable.test'>;
}
