// flow-typed signature: b8be794aedecd506e99122a30d84816c
// flow-typed version: <<STUB>>/react-scroll-up_v^1.3.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scroll-up'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scroll-up' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scroll-up/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scroll-up/index' {
  declare module.exports: $Exports<'react-scroll-up'>;
}
declare module 'react-scroll-up/index.js' {
  declare module.exports: $Exports<'react-scroll-up'>;
}
declare module 'react-scroll-up/test/test.jsx' {
  declare module.exports: $Exports<'react-scroll-up/test/test'>;
}
