// flow-typed signature: 646b6d7cd3d9e4801e67f75d367a2a4b
// flow-typed version: <<STUB>>/react-app-rewire-graphql-tag_v^1.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-graphql-tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-graphql-tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-app-rewire-graphql-tag/index' {
  declare module.exports: $Exports<'react-app-rewire-graphql-tag'>;
}
declare module 'react-app-rewire-graphql-tag/index.js' {
  declare module.exports: $Exports<'react-app-rewire-graphql-tag'>;
}
