// flow-typed signature: 5dbaf6b9868762ae2e3818744218b0ca
// flow-typed version: <<STUB>>/reg-keygen-git-hash-plugin_v^0.7.6/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reg-keygen-git-hash-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reg-keygen-git-hash-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reg-keygen-git-hash-plugin/lib/commit-explorer' {
  declare module.exports: any;
}

declare module 'reg-keygen-git-hash-plugin/lib/git-cmd-client' {
  declare module.exports: any;
}

declare module 'reg-keygen-git-hash-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reg-keygen-git-hash-plugin/lib/commit-explorer.js' {
  declare module.exports: $Exports<'reg-keygen-git-hash-plugin/lib/commit-explorer'>;
}
declare module 'reg-keygen-git-hash-plugin/lib/git-cmd-client.js' {
  declare module.exports: $Exports<'reg-keygen-git-hash-plugin/lib/git-cmd-client'>;
}
declare module 'reg-keygen-git-hash-plugin/lib/index.js' {
  declare module.exports: $Exports<'reg-keygen-git-hash-plugin/lib/index'>;
}
