// flow-typed signature: fb8c11d7d3186ca26570e54764c3579b
// flow-typed version: <<STUB>>/sanitize.css_v^6.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
