// flow-typed signature: 4762985290893d2d252e3bb3c03e886d
// flow-typed version: <<STUB>>/sanitize.css_v^6.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
