// flow-typed signature: c48672b561175311feac808fcf93add5
// flow-typed version: <<STUB>>/storybook-addon-apollo-graphql_v^2.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-apollo-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-apollo-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-apollo-graphql/__tests__/test' {
  declare module.exports: any;
}

declare module 'storybook-addon-apollo-graphql/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-apollo-graphql/__tests__/test.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-graphql/__tests__/test'>;
}
declare module 'storybook-addon-apollo-graphql/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-apollo-graphql/dist/index'>;
}
