// flow-typed signature: c4fe2be80b8baae6b86a466d3a6ffeec
// flow-typed version: <<STUB>>/swivel_v^4.0.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swivel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swivel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swivel/dist/swivel' {
  declare module.exports: any;
}

declare module 'swivel/dist/swivel.min' {
  declare module.exports: any;
}

declare module 'swivel/page' {
  declare module.exports: any;
}

declare module 'swivel/serialization' {
  declare module.exports: any;
}

declare module 'swivel/swivel' {
  declare module.exports: any;
}

declare module 'swivel/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swivel/dist/swivel.js' {
  declare module.exports: $Exports<'swivel/dist/swivel'>;
}
declare module 'swivel/dist/swivel.min.js' {
  declare module.exports: $Exports<'swivel/dist/swivel.min'>;
}
declare module 'swivel/page.js' {
  declare module.exports: $Exports<'swivel/page'>;
}
declare module 'swivel/serialization.js' {
  declare module.exports: $Exports<'swivel/serialization'>;
}
declare module 'swivel/swivel.js' {
  declare module.exports: $Exports<'swivel/swivel'>;
}
declare module 'swivel/worker.js' {
  declare module.exports: $Exports<'swivel/worker'>;
}
