// flow-typed signature: c8feb452434611e76f53676cdddda98d
// flow-typed version: <<STUB>>/@aws-amplify/auth_v^1.0.5/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@aws-amplify/auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@aws-amplify/auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@aws-amplify/auth/dist/aws-amplify-auth' {
  declare module.exports: any;
}

declare module '@aws-amplify/auth/dist/aws-amplify-auth.min' {
  declare module.exports: any;
}

declare module '@aws-amplify/auth/lib/Auth' {
  declare module.exports: any;
}

declare module '@aws-amplify/auth/lib/index' {
  declare module.exports: any;
}

declare module '@aws-amplify/auth/lib/types/Auth' {
  declare module.exports: any;
}

declare module '@aws-amplify/auth/lib/types/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@aws-amplify/auth/dist/aws-amplify-auth.js' {
  declare module.exports: $Exports<'@aws-amplify/auth/dist/aws-amplify-auth'>;
}
declare module '@aws-amplify/auth/dist/aws-amplify-auth.min.js' {
  declare module.exports: $Exports<'@aws-amplify/auth/dist/aws-amplify-auth.min'>;
}
declare module '@aws-amplify/auth/lib/Auth.js' {
  declare module.exports: $Exports<'@aws-amplify/auth/lib/Auth'>;
}
declare module '@aws-amplify/auth/lib/index.js' {
  declare module.exports: $Exports<'@aws-amplify/auth/lib/index'>;
}
declare module '@aws-amplify/auth/lib/types/Auth.js' {
  declare module.exports: $Exports<'@aws-amplify/auth/lib/types/Auth'>;
}
declare module '@aws-amplify/auth/lib/types/index.js' {
  declare module.exports: $Exports<'@aws-amplify/auth/lib/types/index'>;
}
