export const EDIT_EVENT_BASICS_FORM_NAME = 'EditEventBasics'
export const EDIT_EVENT_IMAGES_FORM_NAME = 'EditEventImages'
export const EDIT_EVENT_TAGS_FORM_NAME = 'EditEventTags'
export const EDIT_EVENT_TALENTS_FORM_NAME = 'EditEventTalents'
export const EDIT_EVENT_TIMES_FORM_NAME = 'EditEventTimes'
