version: 2

aliases:
  - &working_directory 
    ~/project
  - &node_docker_image
    - image: circleci/node:10.8-browsers
  - &restore_yarn_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-
  - &save_yarn_cache
    save_cache:
      key: v1-dependencies-{{ checksum "yarn.lock" }}
      paths:
        - node_modules
  - &yarn_install
    run: yarn install --non-interactive --frozen-lockfile

jobs:
  install:
    working_directory: *working_directory
    docker: *node_docker_image
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_yarn_cache
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: *working_directory
          paths: build
  deploy_to_staging:
    working_directory: *working_directory
    docker: *node_docker_image
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - *restore_yarn_cache
      - *yarn_install
      - *save_yarn_cache
      - run:
          name: Deploy master to staging
          command: ./node_modules/.bin/firebase deploy --project artfullylondon-staging-admin --token=$FIREBASE_DEPLOY_TOKEN
  visual_regression:
    working_directory: *working_directory
    docker: *node_docker_image
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_yarn_cache
      - run: yarn run screenshot
      - run: yarn run screenshot:regression

workflows:
  version: 2
  install_and_optionally_deploy:
    jobs:
      - install
      - visual_regression:
          filters:
            branches:
              ignore:
                - master
      - deploy_to_staging:
          requires:
            - install
          filters:
            branches:
              only:
                - master
