version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10.8-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn build
      - store_artifacts:
          path: ~/project/build

workflows:
  version: 2
  install:
    jobs:
      - install
