export const WHEELCHAIR_ACCESS_TYPE_FULL_ACCESS = 'FullAccess'
export const WHEELCHAIR_ACCESS_TYPE_PARTIAL_ACCESS = 'PartialAccess'
export const WHEELCHAIR_ACCESS_TYPE_NO_ACCESS = 'NoAccess'
export const WHEELCHAIR_ACCESS_TYPE_UNKNOWN = 'Unknown'
export const WHEELCHAIR_ACCESS_TYPE_NOT_APPLICABLE = 'NotApplicable'

export const DISABLED_BATHROOM_TYPE_PRESENT = 'Present'
export const DISABLED_BATHROOM_TYPE_NOT_PRESENT = 'NotPresent'
export const DISABLED_BATHROOM_TYPE_UNKNOWN = 'Unknown'
export const DISABLED_BATHROOM_TYPE_NOT_APPLICABLE = 'NotApplicable'

export const HEARING_FACILITIES_TYPE_HEARING_LOOPS = 'HearingLoops'
export const HEARING_FACILITIES_TYPE_PARTIAL_HEARING_LOOPS = 'PartialHearingLoops'
export const HEARING_FACILITIES_TYPE_NO_HEARING_LOOPS = 'NoHearingLoops'
export const HEARING_FACILITIES_TYPE_UNKNOWN = 'Unknown'
export const HEARING_FACILITIES_TYPE_NOT_APPLICABLE = 'NotApplicable'

export const ALLOWED_WHEELCHAIR_ACCESS_TYPES = [
  WHEELCHAIR_ACCESS_TYPE_FULL_ACCESS,
  WHEELCHAIR_ACCESS_TYPE_PARTIAL_ACCESS,
  WHEELCHAIR_ACCESS_TYPE_NO_ACCESS,
  WHEELCHAIR_ACCESS_TYPE_UNKNOWN,
  WHEELCHAIR_ACCESS_TYPE_NOT_APPLICABLE
]

export const WHEELCHAIR_ACCESS_TYPE_DROPDOWN_OPTIONS = [
  {
    value: WHEELCHAIR_ACCESS_TYPE_NOT_APPLICABLE,
    label: 'Not applicable'
  },
  {
    value: WHEELCHAIR_ACCESS_TYPE_FULL_ACCESS,
    label: 'Access to all spaces'
  },
  {
    value: WHEELCHAIR_ACCESS_TYPE_PARTIAL_ACCESS,
    label: 'Access to some spaces'
  },
  { value: WHEELCHAIR_ACCESS_TYPE_NO_ACCESS, label: 'No access' },
  { value: WHEELCHAIR_ACCESS_TYPE_UNKNOWN, label: 'Unknown' }
]

export const ALLOWED_DISABLED_BATHROOM_TYPES = [
  DISABLED_BATHROOM_TYPE_PRESENT,
  DISABLED_BATHROOM_TYPE_NOT_PRESENT,
  DISABLED_BATHROOM_TYPE_UNKNOWN,
  DISABLED_BATHROOM_TYPE_NOT_APPLICABLE
]

export const DISABLED_BATHROOM_TYPE_DROPDOWN_OPTIONS = [
  {
    value: DISABLED_BATHROOM_TYPE_NOT_APPLICABLE,
    label: 'Not applicable'
  },
  { value: DISABLED_BATHROOM_TYPE_PRESENT, label: 'Present' },
  { value: DISABLED_BATHROOM_TYPE_NOT_PRESENT, label: 'Not present' },
  { value: DISABLED_BATHROOM_TYPE_UNKNOWN, label: 'Unknown' }
]

export const ALLOWED_HEARING_FACILITIES_TYPES = [
  HEARING_FACILITIES_TYPE_HEARING_LOOPS,
  HEARING_FACILITIES_TYPE_PARTIAL_HEARING_LOOPS,
  HEARING_FACILITIES_TYPE_NO_HEARING_LOOPS,
  HEARING_FACILITIES_TYPE_UNKNOWN,
  HEARING_FACILITIES_TYPE_NOT_APPLICABLE
]

export const HEARING_FACILITIES_TYPE_DROPDOWN_OPTIONS = [
  {
    value: HEARING_FACILITIES_TYPE_NOT_APPLICABLE,
    label: 'Not applicable'
  },
  {
    value: HEARING_FACILITIES_TYPE_HEARING_LOOPS,
    label: 'Hearing loops in all spaces'
  },
  {
    value: HEARING_FACILITIES_TYPE_PARTIAL_HEARING_LOOPS,
    label: 'Hearing loops in some spaces'
  },
  {
    value: HEARING_FACILITIES_TYPE_NO_HEARING_LOOPS,
    label: 'No hearing loops'
  },
  { value: HEARING_FACILITIES_TYPE_UNKNOWN, label: 'Unknown' }
]
