export const BROWSER_WIDTH_THRESHOLD = 992

export const BROWSER_WIDTH_TYPE_NARROW = 'narrow'
export const BROWSER_WIDTH_TYPE_WIDE = 'wide'

export const ALLOWED_BROWSER_WIDTH_TYPES = [
  BROWSER_WIDTH_TYPE_NARROW,
  BROWSER_WIDTH_TYPE_WIDE
]

export const ARROW_UP_KEYCODE = 38
export const ARROW_DOWN_KEYCODE = 40
