export const ENTITY_TYPE_EVENT = 'event'
export const ENTITY_TYPE_EVENT_SERIES = 'event-series'
export const ENTITY_TYPE_VENUE = 'venue'
export const ENTITY_TYPE_TALENT = 'talent'
export const ENTITY_TYPE_TAG = 'tag'
export const ENTITY_TYPE_USER = 'user'
export const ENTITY_TYPE_ALL = 'all'

export const EDITABLE_ENTITY_TYPES = [
  ENTITY_TYPE_EVENT,
  ENTITY_TYPE_EVENT_SERIES,
  ENTITY_TYPE_VENUE,
  ENTITY_TYPE_TALENT
]

export const ALL_ENTITY_TYPES = [
  ENTITY_TYPE_EVENT,
  ENTITY_TYPE_EVENT_SERIES,
  ENTITY_TYPE_TALENT,
  ENTITY_TYPE_VENUE,
  ENTITY_TYPE_TAG,
  ENTITY_TYPE_USER
]

export const WATCHABLE_ENTITY_TYPES = [
  ENTITY_TYPE_EVENT,
  ENTITY_TYPE_EVENT_SERIES,
  ENTITY_TYPE_TALENT,
  ENTITY_TYPE_VENUE,
  ENTITY_TYPE_TAG
]

export const DEFAULT_ENTITY_CARD_HEIGHT = 175

export const PENDING_STATUS = 'Pending'
export const ACTIVE_STATUS = 'Active'
export const DELETED_STATUS = 'Deleted'
export const MERGED_STATUS = 'Merged'
