export const ENTITY_TYPE_EVENT = 'event'
export const ENTITY_TYPE_EVENT_SERIES = 'event-series'
export const ENTITY_TYPE_VENUE = 'venue'
export const ENTITY_TYPE_TALENT = 'talent'
export const ENTITY_TYPE_TAG = 'tag'
export const ENTITY_TYPE_USER = 'user'
export const ENTITY_TYPE_ALL = 'all'

export const EDITABLE_ENTITY_TYPES = [
  ENTITY_TYPE_EVENT,
  ENTITY_TYPE_EVENT_SERIES,
  ENTITY_TYPE_VENUE,
  ENTITY_TYPE_TALENT
]

export const ALL_ENTITY_TYPES = [
  ENTITY_TYPE_EVENT,
  ENTITY_TYPE_EVENT_SERIES,
  ENTITY_TYPE_TALENT,
  ENTITY_TYPE_VENUE,
  ENTITY_TYPE_TAG,
  ENTITY_TYPE_USER
]

export const WATCHABLE_ENTITY_TYPES = [
  ENTITY_TYPE_EVENT,
  ENTITY_TYPE_EVENT_SERIES,
  ENTITY_TYPE_TALENT,
  ENTITY_TYPE_VENUE,
  ENTITY_TYPE_TAG
]

export const DEFAULT_ENTITY_CARD_HEIGHT = 175

export const GET_ENTITY = 'entity/GET_ENTITY'
export const GET_ENTITY_STARTED = 'entity/GET_ENTITY_STARTED'
export const GET_ENTITY_SUCCEEDED = 'entity/GET_ENTITY_SUCCEEDED'
export const GET_ENTITY_FAILED = 'entity/GET_ENTITY_FAILED'

export const SAVE_ENTITY = 'entity/SAVE_ENTITY'

export const GET_ENTITY_FOR_EDIT = 'entity/GET_ENTITY_FOR_EDIT'
export const GET_ENTITY_FOR_EDIT_STARTED = 'entity/GET_ENTITY_FOR_EDIT_STARTED'
export const GET_ENTITY_FOR_EDIT_SUCCEEDED =
  'entity/GET_ENTITY_FOR_EDIT_SUCCEEDED'
export const GET_ENTITY_FOR_EDIT_FAILED = 'entity/GET_ENTITY_FOR_EDIT_FAILED'

export const RESET_ENTITY_FOR_EDIT = 'entity/RESET_ENTITY_FOR_EDIT'
export const UPDATE_ENTITY_FOR_EDIT = 'entity/UPDATE_ENTITY_FOR_EDIT'

export const AUTOCOMPLETE_SEARCH = 'entity/AUTOCOMPLETE_SEARCH'
export const AUTOCOMPLETE_SEARCH_SUCCEEDED =
  'entity/AUTOCOMPLETE_SEARCH_SUCCEEDED'

export const GET_SUB_ENTITY = 'entity/GET_SUB_ENTITY'
export const GET_SUB_ENTITY_STARTED = 'entity/GET_SUB_ENTITY_STARTED'
export const GET_SUB_ENTITY_FINISHED = 'entity/GET_SUB_ENTITY_FINISHED'

export const CREATE_TALENT_FOR_EVENT = 'entity/CREATE_TALENT_FOR_EVENT'

export const GET_EVENT_AS_COPY = 'entity/GET_EVENT_AS_COPY'
export const GET_EVENT_AS_COPY_STARTED = 'entity/GET_EVENT_AS_COPY_STARTED'
export const GET_EVENT_AS_COPY_SUCCEEDED = 'entity/GET_EVENT_AS_COPY_SUCCEEDED'
export const GET_EVENT_AS_COPY_FAILED = 'entity/GET_EVENT_AS_COPY_FAILED'

export const TALENT_SELECTED = 'entity/TALENT_SELECTED'

export const PENDING_STATUS = 'Pending'
export const ACTIVE_STATUS = 'Active'
export const DELETED_STATUS = 'Deleted'
export const MERGED_STATUS = 'Merged'
