export const GET_VENUE_EVENT_MONITORS = 'monitors/GET_VENUE_EVENT_MONITORS'
export const GET_VENUE_EVENT_MONITORS_STARTED = 'monitors/GET_VENUE_EVENT_MONITORS_STARTED'
export const GET_VENUE_EVENT_MONITORS_SUCCEEDED = 'monitors/GET_VENUE_EVENT_MONITORS_SUCCEEDED'
export const GET_VENUE_EVENT_MONITORS_FAILED = 'monitors/GET_VENUE_EVENT_MONITORS_FAILED'

export const GET_VENUE_EVENT_MONITOR = 'monitors/GET_VENUE_EVENT_MONITOR'
export const GET_VENUE_EVENT_MONITOR_STARTED = 'monitors/GET_VENUE_EVENT_MONITOR_STARTED'
export const GET_VENUE_EVENT_MONITOR_SUCCEEDED = 'monitors/GET_VENUE_EVENT_MONITOR_SUCCEEDED'
export const GET_VENUE_EVENT_MONITOR_FAILED = 'monitors/GET_VENUE_EVENT_MONITOR_FAILED'

export const UPDATE_VENUE_EVENT_MONITOR = 'monitors/UPDATE_VENUE_EVENT_MONITOR'
export const UPDATE_VENUE_EVENT_MONITOR_SUCCEEDED = 'monitors/UPDATE_VENUE_EVENT_MONITOR_SUCCEEDED'

export const CHANGE_IGNORED_VENUE_EVENT_MONITORS_VISIBILITY = 'monitors/CHANGE_IGNORED_VENUE_EVENT_MONITORS_VISIBILITY'

export const GET_VENUE_MONITOR = 'monitors/GET_VENUE_MONITOR'
export const GET_VENUE_MONITOR_STARTED = 'monitors/GET_VENUE_MONITOR_STARTED'
export const GET_VENUE_MONITOR_SUCCEEDED = 'monitors/GET_VENUE_MONITOR_SUCCEEDED'
export const GET_VENUE_MONITOR_FAILED = 'monitors/GET_VENUE_MONITOR_FAILED'

export const UPDATE_VENUE_MONITOR = 'monitors/UPDATE_VENUE_MONITOR'
export const UPDATE_VENUE_MONITOR_SUCCEEDED = 'monitors/UPDATE_VENUE_MONITOR_SUCCEEDED'
