export const NOTIFICATION_TYPE_SUCCESS = 'Success'
export const NOTIFICATION_TYPE_ERROR = 'Error'

export const ALLOWED_NOTIFICATION_TYPES = [
  NOTIFICATION_TYPE_SUCCESS,
  NOTIFICATION_TYPE_ERROR
]

export const ADD_NOTIFICATION = 'notifications/ADD_NOTIFICATION'
export const NOTIFICATION_ADDED = 'notifications/NOTIFICATION_ADDED'
export const REMOVE_NOTIFICATION = 'notifications/REMOVE_NOTIFICATION'
