export const NOTIFICATION_TYPE_SUCCESS = 'Success'
export const NOTIFICATION_TYPE_ERROR = 'Error'

export const ALLOWED_NOTIFICATION_TYPES = [
  NOTIFICATION_TYPE_SUCCESS,
  NOTIFICATION_TYPE_ERROR
]

export const DEFAULT_NOTIFICATION_DISPLAY_TIME_SECS = 5
