export const GET_ENTITY_COUNTS = 'status/GET_ENTITY_COUNTS'
export const GET_ENTITY_COUNTS_STARTED = 'status/GET_ENTITY_COUNTS_STARTED'
export const GET_ENTITY_COUNTS_SUCCEEDED = 'status/GET_ENTITY_COUNTS_SUCCEEDED'
export const GET_ENTITY_COUNTS_FAILED = 'status/GET_ENTITY_COUNTS_FAILED'
