export const VENUE_TYPE_THEATRE = 'Theatre'
export const VENUE_TYPE_ART_GALLERY = 'Art Gallery'
export const VENUE_TYPE_CONCERT_HALL = 'Concert Hall'
export const VENUE_TYPE_EXHIBITION_HALL = 'Exhibition Hall'
export const VENUE_TYPE_PERFORMING_ARTS_CENTRE = 'Performing Arts Centre'
export const VENUE_TYPE_MUSEUM = 'Museum'
export const VENUE_TYPE_CHURCH = 'Church'
export const VENUE_TYPE_CINEMA = 'Cinema'
export const VENUE_TYPE_OTHER = 'Other'

export const ALLOWED_VENUE_TYPES = [
  VENUE_TYPE_THEATRE,
  VENUE_TYPE_ART_GALLERY,
  VENUE_TYPE_CONCERT_HALL,
  VENUE_TYPE_EXHIBITION_HALL,
  VENUE_TYPE_PERFORMING_ARTS_CENTRE,
  VENUE_TYPE_MUSEUM,
  VENUE_TYPE_CHURCH,
  VENUE_TYPE_CINEMA,
  VENUE_TYPE_OTHER
]
