export const LOGGED_OUT = 'auth/LOGGED_OUT'
export const LOG_IN = 'auth/LOG_IN'
export const LOG_IN_SUCCEEDED = 'auth/LOG_IN_SUCCEEDED'
export const LOG_IN_FAILED = 'auth/LOG_IN_FAILED'
export const LOG_OUT = 'auth/LOG_OUT'
export const ATTEMPT_AUTO_LOG_IN = 'auth/ATTEMPT_AUTO_LOG_IN'
export const AUTO_LOG_IN_ATTEMPTED = 'auth/AUTO_LOG_IN_ATTEMPTED'
