export const LOGGED_OUT = 'auth/LOGGED_OUT'
export const SUBMIT_LOGIN = 'auth/SUBMIT_LOGIN'
export const LOG_IN_SUCCEEDED = 'auth/LOG_IN_SUCCEEDED'
export const LOG_IN_FAILED = 'auth/LOG_IN_FAILED'
export const LOG_OUT = 'auth/LOG_OUT'
